name: build-test-deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-test-deploy:
    name: Build-Test-Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.x']
        mongodb-version: ['4.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build codebase
        run: yarn build
        env:
          CI: true

      - name: Run unit tests
        run: yarn test

      ### DEPLOY SECTION START

      - name: Set AWS credentials globally
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mineral-exploration-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      ##### Run Migrator task

      - name: Fill in the new image ID in Migrator task definition
        id: task-def-migrator
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/cd/task-definition-migrator.json
          container-name: mineral-exploration-api-migrator
          image: ${{ steps.build-image.outputs.image }}

      - name: Show task definition
        run: cat ${{ steps.task-def-migrator.outputs.task-definition }}

      - name: Deploy Migrator task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-migrator.outputs.task-definition }}
          service: mineral-exploration-api-migrator
          cluster: object-undefined

      - name: Run migrator task once
        run: aws ecs run-task --cluster object-undefined --count 1 --launch-type EC2 --task-definition $(aws ecs list-task-definitions | grep mineral-exploration-api-migrator | tail -1 | sed 's,"\|\,,,g')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      ##### Deploy API service

      - name: Fill in the new image ID in API task definition
        id: task-def-api
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/cd/task-definition-api.json
          container-name: mineral-exploration-api
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy API task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-api.outputs.task-definition }}
          service: mineral-exploration-api
          cluster: object-undefined

      ##### Deploy Handlers service

      - name: Fill in the new image ID in Handlers task definition
        id: task-def-handlers
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/cd/task-definition-handlers.json
          container-name: mineral-exploration-api-handlers
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Handlers task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-handlers.outputs.task-definition }}
          service: mineral-exploration-api-handlers
          cluster: object-undefined
